### ISSUE TITLE
Failed to compile on Windows

### ISSUE THREAD

**Issue by tuxzz** [rust-math/fftw#59]
````x fftw-3.3.6-pl1/doc/fftw3.info-1
x fftw-3.3.6-pl1/doc/fftw3.info-2
x fftw-3.3.6-pl1/tools/
x fftw-3.3.6-pl1/tools/Makefile.am
x fftw-3.3.6-pl1/tools/fftw-wisdom-to-conf.1
x fftw-3.3.6-pl1/tools/fftwf-wisdom.1
x fftw-3.3.6-pl1/tools/Makefile.in
x fftw-3.3.6-pl1/tools/fftw-wisdom-to-conf.in
x fftw-3.3.6-pl1/tools/fftw_wisdom.1.in
x fftw-3.3.6-pl1/tools/fftw-wisdom.c
thread 'main' panicked at 'failed to execute `"./configure" "--enable-static" "--with-pic" "--enable-single"`: The system cannot find the file specified. (os error 2)', C:\Users\username\.cargo\registry\src\github.com-1ecc6299db9ec823\fftw-src-0.2.3\build.rs:101:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
````
System: Windows 10 Pro 17134 x64 
Rust Toolchain: nightly-2019-01-26-x86_64-pc-windows-gnu 
System Compiler: MSVC 2017

FFTW offically supports Windows. How can I build this crate on windows?

**Comment by termoshtt** [comment]
Windows is not supported currently.

> FFTW offically supports Windows.

Thanks info. I guess we need to exntend fftw-src crate for windows to download DLL from http://www.fftw.org/install/windows.html and link it.

**Comment by termoshtt** [comment]
Windows support is launched in fftw-0.6.0 both for `source` and `intel-mkl` features. I close this PR. Please re-open it still does not working.
