### ISSUE TITLE
travis not configured correctly

### ISSUE THREAD

**Issue by amilajack** [rust-math/fftw#62]
It seems that only WIP tests are running (not Travsi tests)

<img width="559" alt="Screen Shot 2019-04-19 at 1 52 38 PM" src="https://user-images.githubusercontent.com/6374832/56443672-7f3a4b80-62aa-11e9-940c-7c3b03a5a5c0.png">

**Comment by termoshtt** [comment]
Thanks, it runs only for Pushed branch. I fixed
