### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by Unlikus** [rust-math/fftw#72]
In the documentation of FFTW3 it is stated that the creation of a plan is not thread save.
http://www.fftw.org/fftw3_doc/Thread-safety.html
Is this binding thread save? I cant find any mechanism which would prevent two threads to create 2 Plans at the same time.

**Comment by termoshtt** [comment]
There exists a global lock `FFTW_MUTEX` at https://github.com/rust-math/fftw/blob/master/fftw/src/lib.rs#L55, and `excall!` gets this lock for all raw FFTW API except for `fftw_execute`.

**Comment by termoshtt** [comment]
Please reopen if not resolved
