### ISSUE TITLE
Bundle FFTW source code with fftw-src

### ISSUE THREAD

**Issue by hombit** [rust-math/fftw#83]
Downloading the source code of FFTW on every compilation could be inefficient or even impossible in some environments. For example, network access is blocked on docs.rs, [that caused `fftw-src 0.3.1` docs build fail](https://docs.rs/crate/fftw-src/0.3.1/builds), and can cause similar problem for dependent crates. This is why I propose to include FFTW source code into `fftw-src` crate.

**Comment by LingMan** [comment]
That would also get rid of the reqwest dependency which takes a significant amount of time to compile by itself. +1

**Comment by termoshtt** [comment]
I close this because #88 have realized source code bundling. Downloading issue is inherited into #89
