### ISSUE TITLE
fftw-src doesn't compile

### ISSUE THREAD

**Issue by hombit** [rust-math/fftw#99]
Probably the problem is with `fs_extra 1.2`:

```
error[E0063]: missing field `content_only` in initializer of `fs_extra::dir::CopyOptions`
  --> fftw-src/build.rs:52:10
   |
52 |         &fs_extra::dir::CopyOptions {
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `content_only`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0063`.
error: could not compile `fftw-src`.
```

**Comment by manuelmenzella** [comment]
Thanks for fixing this! I am new to Rust; what happens now? When will the new crate version be released?

**Comment by hombit** [comment]
@manuelmenzella As a temporary fix you can specify that you would like to use `fs_extra == 1.1` in your `Cargo.toml`, an example from my crate:

https://github.com/hombit/light-curve/blob/c4ccebc691fbc679a51499cb736951d8351f6544/light-curve-feature/Cargo.toml#L36-L38

**Comment by termoshtt** [comment]
I've release 0.3.3 which fixes this issue https://crates.io/crates/fftw-src/0.3.3

**Comment by manuelmenzella** [comment]
Thank you both!
